version: "3.9"

services:
  front:
      image: frontendd
      networks:
       - bridge
      container_name: frontend
      build:
        context: .
        dockerfile: Dockerfile
      ports:
       - "3030:3030"

networks:
  bridge :
    external:
      name: app